### PR TITLE
Added optional tablespoon and teaspoon conversion + small fixes

### PR DESCRIPTION
**Pull request by f-to**
Added three options :
- tablespoon(s)/tbsp to mL conversion
- teaspoon(s)/tsp to mL conversion
- "deg(ree(s))" without trailing Fahrenheit conversion

Useful test pages :
https://blog.prepscholar.com/how-many-teaspoons-in-a-tablespoon
https://thisdelicioushouse.com/blueberry-lemon-bundt-cake/

### CODE REVIEW

**Comment by m1l** [comment]
Was there a specific reason for adding both convertTablespoon and convertTeaspoon as separate options? Is there a use case where a user would want to enable one and not the other?

**Comment by f-to** [comment]
The reason is teaspoon is a very small quantity (5 mL) and measuring it in mL is not that easy without proper cookware.
Feel free to reject it and I will group it under the same option.

**Comment by m1l** [comment]
That makes sense. Quick look and I have not found recipes using more than 2 tsp as 3 tsp is already 1tbsp.
I'll just download it tomorrow to check before merging. 
Just to share the original idea for tsp/tbsp that I have not had time to implement yet - I thought to use mass/weight by catching a word after the t(b)sp... so 1 tbsp (of)? sugar would be 12.6g, while flour would weight 7.8g, and honey 22g; and maybe showing both ml and g; That would be used for most common ingredients after used after t(b)sp, and the rest would be just ml as default. Maybe doing the same with cups as I have found that cooking with mass is much easier than with volumes.

**Comment by m1l** [comment]
I created a page for testing

https://github.com/m1l/Everything-Metric-Firefox/blob/master/PageForTesting.md

and noticed that degree option results in this kind of conversions

`82 degrees °​【𝟮𝟴°𝗖】Fahrenheit`

so it would be better if there is a word Fahrenheit to have the conversion after it

**Comment by f-to** [comment]
I will correct it, thank you.

**Pull request merged**
